// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7zrLO32dXdDq--y5NEPdZ4adcl2bVOZY',
    appId: '1:319264081179:web:1f14ab7c6f3ff343b83fbe',
    messagingSenderId: '319264081179',
    projectId: 'dart-quizz',
    authDomain: 'dart-quizz.firebaseapp.com',
    storageBucket: 'dart-quizz.firebasestorage.app',
    measurementId: 'G-KFTSZL3J2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcxtZX7uaNzvtt9VN3q6v3NhFltCuIzC4',
    appId: '1:319264081179:android:d476a04395f94fb1b83fbe',
    messagingSenderId: '319264081179',
    projectId: 'dart-quizz',
    storageBucket: 'dart-quizz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpDvkuCnfByL6xZ4bGcsZXP8OFvL3Ai-g',
    appId: '1:319264081179:ios:f656091b6db92f03b83fbe',
    messagingSenderId: '319264081179',
    projectId: 'dart-quizz',
    storageBucket: 'dart-quizz.firebasestorage.app',
    iosBundleId: 'com.example.dartquizz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpDvkuCnfByL6xZ4bGcsZXP8OFvL3Ai-g',
    appId: '1:319264081179:ios:f656091b6db92f03b83fbe',
    messagingSenderId: '319264081179',
    projectId: 'dart-quizz',
    storageBucket: 'dart-quizz.firebasestorage.app',
    iosBundleId: 'com.example.dartquizz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7zrLO32dXdDq--y5NEPdZ4adcl2bVOZY',
    appId: '1:319264081179:web:0c70b73c4d316ac0b83fbe',
    messagingSenderId: '319264081179',
    projectId: 'dart-quizz',
    authDomain: 'dart-quizz.firebaseapp.com',
    storageBucket: 'dart-quizz.firebasestorage.app',
    measurementId: 'G-E1S9PYRB1C',
  );
}
